server:
  port: 80
#  ssl:
#    key-store: classpath:keystore.jks
#    key-store-password: 123456
#    key-alias: tomcat
logging:
  level:
    root: info
  file:
    name: logs/video-conference-manager.log
spring:
  mvc:
    async:
      request-timeout: -1

